// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"orchestrator_service/database/pgsql/model"
)

func newSagaMap(db *gorm.DB, opts ...gen.DOOption) sagaMap {
	_sagaMap := sagaMap{}

	_sagaMap.sagaMapDo.UseDB(db, opts...)
	_sagaMap.sagaMapDo.UseModel(&model.SagaMap{})

	tableName := _sagaMap.sagaMapDo.TableName()
	_sagaMap.ALL = field.NewAsterisk(tableName)
	_sagaMap.ID = field.NewString(tableName, "id")
	_sagaMap.Status = field.NewString(tableName, "status")
	_sagaMap.ExecutionMode = field.NewString(tableName, "execution_mode")
	_sagaMap.CurrentStep = field.NewInt(tableName, "current_step")
	_sagaMap.Version = field.NewInt(tableName, "version")
	_sagaMap.Context = field.NewString(tableName, "context")
	_sagaMap.Steps = field.NewString(tableName, "steps")
	_sagaMap.CompletedSteps = field.NewInt(tableName, "completed_steps")
	_sagaMap.FailedSteps = field.NewInt(tableName, "failed_steps")
	_sagaMap.RetryCount = field.NewInt(tableName, "retry_count")
	_sagaMap.MaxRetryCount = field.NewInt(tableName, "max_retry_count")
	_sagaMap.CreatedAt = field.NewTime(tableName, "created_at")
	_sagaMap.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sagaMap.CorrelationID = field.NewString(tableName, "correlation_id")
	_sagaMap.TraceID = field.NewString(tableName, "trace_id")
	_sagaMap.LockedBy = field.NewString(tableName, "locked_by")
	_sagaMap.LockExpiry = field.NewTime(tableName, "lock_expiry")

	_sagaMap.fillFieldMap()

	return _sagaMap
}

type sagaMap struct {
	sagaMapDo sagaMapDo

	ALL            field.Asterisk
	ID             field.String
	Status         field.String
	ExecutionMode  field.String
	CurrentStep    field.Int
	Version        field.Int
	Context        field.String
	Steps          field.String
	CompletedSteps field.Int
	FailedSteps    field.Int
	RetryCount     field.Int
	MaxRetryCount  field.Int
	CreatedAt      field.Time
	UpdatedAt      field.Time
	CorrelationID  field.String
	TraceID        field.String
	LockedBy       field.String
	LockExpiry     field.Time

	fieldMap map[string]field.Expr
}

func (s sagaMap) Table(newTableName string) *sagaMap {
	s.sagaMapDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sagaMap) As(alias string) *sagaMap {
	s.sagaMapDo.DO = *(s.sagaMapDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sagaMap) updateTableName(table string) *sagaMap {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewString(table, "id")
	s.Status = field.NewString(table, "status")
	s.ExecutionMode = field.NewString(table, "execution_mode")
	s.CurrentStep = field.NewInt(table, "current_step")
	s.Version = field.NewInt(table, "version")
	s.Context = field.NewString(table, "context")
	s.Steps = field.NewString(table, "steps")
	s.CompletedSteps = field.NewInt(table, "completed_steps")
	s.FailedSteps = field.NewInt(table, "failed_steps")
	s.RetryCount = field.NewInt(table, "retry_count")
	s.MaxRetryCount = field.NewInt(table, "max_retry_count")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.CorrelationID = field.NewString(table, "correlation_id")
	s.TraceID = field.NewString(table, "trace_id")
	s.LockedBy = field.NewString(table, "locked_by")
	s.LockExpiry = field.NewTime(table, "lock_expiry")

	s.fillFieldMap()

	return s
}

func (s *sagaMap) WithContext(ctx context.Context) ISagaMapDo { return s.sagaMapDo.WithContext(ctx) }

func (s sagaMap) TableName() string { return s.sagaMapDo.TableName() }

func (s sagaMap) Alias() string { return s.sagaMapDo.Alias() }

func (s sagaMap) Columns(cols ...field.Expr) gen.Columns { return s.sagaMapDo.Columns(cols...) }

func (s *sagaMap) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sagaMap) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 17)
	s.fieldMap["id"] = s.ID
	s.fieldMap["status"] = s.Status
	s.fieldMap["execution_mode"] = s.ExecutionMode
	s.fieldMap["current_step"] = s.CurrentStep
	s.fieldMap["version"] = s.Version
	s.fieldMap["context"] = s.Context
	s.fieldMap["steps"] = s.Steps
	s.fieldMap["completed_steps"] = s.CompletedSteps
	s.fieldMap["failed_steps"] = s.FailedSteps
	s.fieldMap["retry_count"] = s.RetryCount
	s.fieldMap["max_retry_count"] = s.MaxRetryCount
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["correlation_id"] = s.CorrelationID
	s.fieldMap["trace_id"] = s.TraceID
	s.fieldMap["locked_by"] = s.LockedBy
	s.fieldMap["lock_expiry"] = s.LockExpiry
}

func (s sagaMap) clone(db *gorm.DB) sagaMap {
	s.sagaMapDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sagaMap) replaceDB(db *gorm.DB) sagaMap {
	s.sagaMapDo.ReplaceDB(db)
	return s
}

type sagaMapDo struct{ gen.DO }

type ISagaMapDo interface {
	gen.SubQuery
	Debug() ISagaMapDo
	WithContext(ctx context.Context) ISagaMapDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISagaMapDo
	WriteDB() ISagaMapDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISagaMapDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISagaMapDo
	Not(conds ...gen.Condition) ISagaMapDo
	Or(conds ...gen.Condition) ISagaMapDo
	Select(conds ...field.Expr) ISagaMapDo
	Where(conds ...gen.Condition) ISagaMapDo
	Order(conds ...field.Expr) ISagaMapDo
	Distinct(cols ...field.Expr) ISagaMapDo
	Omit(cols ...field.Expr) ISagaMapDo
	Join(table schema.Tabler, on ...field.Expr) ISagaMapDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISagaMapDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISagaMapDo
	Group(cols ...field.Expr) ISagaMapDo
	Having(conds ...gen.Condition) ISagaMapDo
	Limit(limit int) ISagaMapDo
	Offset(offset int) ISagaMapDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISagaMapDo
	Unscoped() ISagaMapDo
	Create(values ...*model.SagaMap) error
	CreateInBatches(values []*model.SagaMap, batchSize int) error
	Save(values ...*model.SagaMap) error
	First() (*model.SagaMap, error)
	Take() (*model.SagaMap, error)
	Last() (*model.SagaMap, error)
	Find() ([]*model.SagaMap, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SagaMap, err error)
	FindInBatches(result *[]*model.SagaMap, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SagaMap) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISagaMapDo
	Assign(attrs ...field.AssignExpr) ISagaMapDo
	Joins(fields ...field.RelationField) ISagaMapDo
	Preload(fields ...field.RelationField) ISagaMapDo
	FirstOrInit() (*model.SagaMap, error)
	FirstOrCreate() (*model.SagaMap, error)
	FindByPage(offset int, limit int) (result []*model.SagaMap, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISagaMapDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sagaMapDo) Debug() ISagaMapDo {
	return s.withDO(s.DO.Debug())
}

func (s sagaMapDo) WithContext(ctx context.Context) ISagaMapDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sagaMapDo) ReadDB() ISagaMapDo {
	return s.Clauses(dbresolver.Read)
}

func (s sagaMapDo) WriteDB() ISagaMapDo {
	return s.Clauses(dbresolver.Write)
}

func (s sagaMapDo) Session(config *gorm.Session) ISagaMapDo {
	return s.withDO(s.DO.Session(config))
}

func (s sagaMapDo) Clauses(conds ...clause.Expression) ISagaMapDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sagaMapDo) Returning(value interface{}, columns ...string) ISagaMapDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sagaMapDo) Not(conds ...gen.Condition) ISagaMapDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sagaMapDo) Or(conds ...gen.Condition) ISagaMapDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sagaMapDo) Select(conds ...field.Expr) ISagaMapDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sagaMapDo) Where(conds ...gen.Condition) ISagaMapDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sagaMapDo) Order(conds ...field.Expr) ISagaMapDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sagaMapDo) Distinct(cols ...field.Expr) ISagaMapDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sagaMapDo) Omit(cols ...field.Expr) ISagaMapDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sagaMapDo) Join(table schema.Tabler, on ...field.Expr) ISagaMapDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sagaMapDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISagaMapDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sagaMapDo) RightJoin(table schema.Tabler, on ...field.Expr) ISagaMapDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sagaMapDo) Group(cols ...field.Expr) ISagaMapDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sagaMapDo) Having(conds ...gen.Condition) ISagaMapDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sagaMapDo) Limit(limit int) ISagaMapDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sagaMapDo) Offset(offset int) ISagaMapDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sagaMapDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISagaMapDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sagaMapDo) Unscoped() ISagaMapDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sagaMapDo) Create(values ...*model.SagaMap) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sagaMapDo) CreateInBatches(values []*model.SagaMap, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sagaMapDo) Save(values ...*model.SagaMap) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sagaMapDo) First() (*model.SagaMap, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SagaMap), nil
	}
}

func (s sagaMapDo) Take() (*model.SagaMap, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SagaMap), nil
	}
}

func (s sagaMapDo) Last() (*model.SagaMap, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SagaMap), nil
	}
}

func (s sagaMapDo) Find() ([]*model.SagaMap, error) {
	result, err := s.DO.Find()
	return result.([]*model.SagaMap), err
}

func (s sagaMapDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SagaMap, err error) {
	buf := make([]*model.SagaMap, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sagaMapDo) FindInBatches(result *[]*model.SagaMap, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sagaMapDo) Attrs(attrs ...field.AssignExpr) ISagaMapDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sagaMapDo) Assign(attrs ...field.AssignExpr) ISagaMapDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sagaMapDo) Joins(fields ...field.RelationField) ISagaMapDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sagaMapDo) Preload(fields ...field.RelationField) ISagaMapDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sagaMapDo) FirstOrInit() (*model.SagaMap, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SagaMap), nil
	}
}

func (s sagaMapDo) FirstOrCreate() (*model.SagaMap, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SagaMap), nil
	}
}

func (s sagaMapDo) FindByPage(offset int, limit int) (result []*model.SagaMap, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sagaMapDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sagaMapDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sagaMapDo) Delete(models ...*model.SagaMap) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sagaMapDo) withDO(do gen.Dao) *sagaMapDo {
	s.DO = *do.(*gen.DO)
	return s
}
