// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q            = new(Query)
	Conversation *conversation
	Group        *group
	PrivateChat  *privateChat
	TempChat     *tempChat
	UserGroup    *userGroup
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Conversation = &Q.Conversation
	Group = &Q.Group
	PrivateChat = &Q.PrivateChat
	TempChat = &Q.TempChat
	UserGroup = &Q.UserGroup
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:           db,
		Conversation: newConversation(db, opts...),
		Group:        newGroup(db, opts...),
		PrivateChat:  newPrivateChat(db, opts...),
		TempChat:     newTempChat(db, opts...),
		UserGroup:    newUserGroup(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Conversation conversation
	Group        group
	PrivateChat  privateChat
	TempChat     tempChat
	UserGroup    userGroup
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		Conversation: q.Conversation.clone(db),
		Group:        q.Group.clone(db),
		PrivateChat:  q.PrivateChat.clone(db),
		TempChat:     q.TempChat.clone(db),
		UserGroup:    q.UserGroup.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		Conversation: q.Conversation.replaceDB(db),
		Group:        q.Group.replaceDB(db),
		PrivateChat:  q.PrivateChat.replaceDB(db),
		TempChat:     q.TempChat.replaceDB(db),
		UserGroup:    q.UserGroup.replaceDB(db),
	}
}

type queryCtx struct {
	Conversation IConversationDo
	Group        IGroupDo
	PrivateChat  IPrivateChatDo
	TempChat     ITempChatDo
	UserGroup    IUserGroupDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Conversation: q.Conversation.WithContext(ctx),
		Group:        q.Group.WithContext(ctx),
		PrivateChat:  q.PrivateChat.WithContext(ctx),
		TempChat:     q.TempChat.WithContext(ctx),
		UserGroup:    q.UserGroup.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
