// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q           = new(Query)
	Group       *group
	PrivateChat *privateChat
	TempChat    *tempChat
	User        *user
	UserGroup   *userGroup
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Group = &Q.Group
	PrivateChat = &Q.PrivateChat
	TempChat = &Q.TempChat
	User = &Q.User
	UserGroup = &Q.UserGroup
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:          db,
		Group:       newGroup(db, opts...),
		PrivateChat: newPrivateChat(db, opts...),
		TempChat:    newTempChat(db, opts...),
		User:        newUser(db, opts...),
		UserGroup:   newUserGroup(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Group       group
	PrivateChat privateChat
	TempChat    tempChat
	User        user
	UserGroup   userGroup
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:          db,
		Group:       q.Group.clone(db),
		PrivateChat: q.PrivateChat.clone(db),
		TempChat:    q.TempChat.clone(db),
		User:        q.User.clone(db),
		UserGroup:   q.UserGroup.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:          db,
		Group:       q.Group.replaceDB(db),
		PrivateChat: q.PrivateChat.replaceDB(db),
		TempChat:    q.TempChat.replaceDB(db),
		User:        q.User.replaceDB(db),
		UserGroup:   q.UserGroup.replaceDB(db),
	}
}

type queryCtx struct {
	Group       IGroupDo
	PrivateChat IPrivateChatDo
	TempChat    ITempChatDo
	User        IUserDo
	UserGroup   IUserGroupDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Group:       q.Group.WithContext(ctx),
		PrivateChat: q.PrivateChat.WithContext(ctx),
		TempChat:    q.TempChat.WithContext(ctx),
		User:        q.User.WithContext(ctx),
		UserGroup:   q.UserGroup.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
