# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import last_offline_time_pb2 as last__offline__time__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in last_offline_time_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LastOfflineTimeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateLastOfflineTime = channel.unary_unary(
                '/grpc.LastOfflineTimeService/UpdateLastOfflineTime',
                request_serializer=last__offline__time__pb2.UpdateLastOfflineTimeRequest.SerializeToString,
                response_deserializer=last__offline__time__pb2.UpdateLastOfflineTimeResponse.FromString,
                _registered_method=True)
        self.GetLastOfflineTime = channel.unary_unary(
                '/grpc.LastOfflineTimeService/GetLastOfflineTime',
                request_serializer=last__offline__time__pb2.GetLastOfflineTimeRequest.SerializeToString,
                response_deserializer=last__offline__time__pb2.GetLastOfflineTimeResponse.FromString,
                _registered_method=True)


class LastOfflineTimeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateLastOfflineTime(self, request, context):
        """更新用户最后离线时间
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLastOfflineTime(self, request, context):
        """获取用户最后离线时间
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LastOfflineTimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateLastOfflineTime': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateLastOfflineTime,
                    request_deserializer=last__offline__time__pb2.UpdateLastOfflineTimeRequest.FromString,
                    response_serializer=last__offline__time__pb2.UpdateLastOfflineTimeResponse.SerializeToString,
            ),
            'GetLastOfflineTime': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLastOfflineTime,
                    request_deserializer=last__offline__time__pb2.GetLastOfflineTimeRequest.FromString,
                    response_serializer=last__offline__time__pb2.GetLastOfflineTimeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.LastOfflineTimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grpc.LastOfflineTimeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LastOfflineTimeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateLastOfflineTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.LastOfflineTimeService/UpdateLastOfflineTime',
            last__offline__time__pb2.UpdateLastOfflineTimeRequest.SerializeToString,
            last__offline__time__pb2.UpdateLastOfflineTimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLastOfflineTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.LastOfflineTimeService/GetLastOfflineTime',
            last__offline__time__pb2.GetLastOfflineTimeRequest.SerializeToString,
            last__offline__time__pb2.GetLastOfflineTimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
