// last_offline_time.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: infrastructure_sdk/grpc/last_offline_time_grpc/proto/last_offline_time.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LastOfflineTimeService_UpdateLastOfflineTime_FullMethodName = "/grpc.LastOfflineTimeService/UpdateLastOfflineTime"
	LastOfflineTimeService_GetLastOfflineTime_FullMethodName    = "/grpc.LastOfflineTimeService/GetLastOfflineTime"
)

// LastOfflineTimeServiceClient is the client API for LastOfflineTimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LastOfflineTimeServiceClient interface {
	// 更新用户最后离线时间
	UpdateLastOfflineTime(ctx context.Context, in *UpdateLastOfflineTimeRequest, opts ...grpc.CallOption) (*UpdateLastOfflineTimeResponse, error)
	// 获取用户最后离线时间
	GetLastOfflineTime(ctx context.Context, in *GetLastOfflineTimeRequest, opts ...grpc.CallOption) (*GetLastOfflineTimeResponse, error)
}

type lastOfflineTimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLastOfflineTimeServiceClient(cc grpc.ClientConnInterface) LastOfflineTimeServiceClient {
	return &lastOfflineTimeServiceClient{cc}
}

func (c *lastOfflineTimeServiceClient) UpdateLastOfflineTime(ctx context.Context, in *UpdateLastOfflineTimeRequest, opts ...grpc.CallOption) (*UpdateLastOfflineTimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateLastOfflineTimeResponse)
	err := c.cc.Invoke(ctx, LastOfflineTimeService_UpdateLastOfflineTime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lastOfflineTimeServiceClient) GetLastOfflineTime(ctx context.Context, in *GetLastOfflineTimeRequest, opts ...grpc.CallOption) (*GetLastOfflineTimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLastOfflineTimeResponse)
	err := c.cc.Invoke(ctx, LastOfflineTimeService_GetLastOfflineTime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LastOfflineTimeServiceServer is the server API for LastOfflineTimeService service.
// All implementations must embed UnimplementedLastOfflineTimeServiceServer
// for forward compatibility.
type LastOfflineTimeServiceServer interface {
	// 更新用户最后离线时间
	UpdateLastOfflineTime(context.Context, *UpdateLastOfflineTimeRequest) (*UpdateLastOfflineTimeResponse, error)
	// 获取用户最后离线时间
	GetLastOfflineTime(context.Context, *GetLastOfflineTimeRequest) (*GetLastOfflineTimeResponse, error)
	mustEmbedUnimplementedLastOfflineTimeServiceServer()
}

// UnimplementedLastOfflineTimeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLastOfflineTimeServiceServer struct{}

func (UnimplementedLastOfflineTimeServiceServer) UpdateLastOfflineTime(context.Context, *UpdateLastOfflineTimeRequest) (*UpdateLastOfflineTimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLastOfflineTime not implemented")
}
func (UnimplementedLastOfflineTimeServiceServer) GetLastOfflineTime(context.Context, *GetLastOfflineTimeRequest) (*GetLastOfflineTimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLastOfflineTime not implemented")
}
func (UnimplementedLastOfflineTimeServiceServer) mustEmbedUnimplementedLastOfflineTimeServiceServer() {
}
func (UnimplementedLastOfflineTimeServiceServer) testEmbeddedByValue() {}

// UnsafeLastOfflineTimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LastOfflineTimeServiceServer will
// result in compilation errors.
type UnsafeLastOfflineTimeServiceServer interface {
	mustEmbedUnimplementedLastOfflineTimeServiceServer()
}

func RegisterLastOfflineTimeServiceServer(s grpc.ServiceRegistrar, srv LastOfflineTimeServiceServer) {
	// If the following call pancis, it indicates UnimplementedLastOfflineTimeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LastOfflineTimeService_ServiceDesc, srv)
}

func _LastOfflineTimeService_UpdateLastOfflineTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLastOfflineTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LastOfflineTimeServiceServer).UpdateLastOfflineTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LastOfflineTimeService_UpdateLastOfflineTime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LastOfflineTimeServiceServer).UpdateLastOfflineTime(ctx, req.(*UpdateLastOfflineTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LastOfflineTimeService_GetLastOfflineTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLastOfflineTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LastOfflineTimeServiceServer).GetLastOfflineTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LastOfflineTimeService_GetLastOfflineTime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LastOfflineTimeServiceServer).GetLastOfflineTime(ctx, req.(*GetLastOfflineTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LastOfflineTimeService_ServiceDesc is the grpc.ServiceDesc for LastOfflineTimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LastOfflineTimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.LastOfflineTimeService",
	HandlerType: (*LastOfflineTimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateLastOfflineTime",
			Handler:    _LastOfflineTimeService_UpdateLastOfflineTime_Handler,
		},
		{
			MethodName: "GetLastOfflineTime",
			Handler:    _LastOfflineTimeService_GetLastOfflineTime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "infrastructure_sdk/grpc/last_offline_time_grpc/proto/last_offline_time.proto",
}
