# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: infrastructure_sdk/grpc/last_offline_time_grpc/proto/last_offline_time.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'infrastructure_sdk/grpc/last_offline_time_grpc/proto/last_offline_time.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nLinfrastructure_sdk/grpc/last_offline_time_grpc/proto/last_offline_time.proto\x12\x04grpc\"/\n\x1cUpdateLastOfflineTimeRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"0\n\x1dUpdateLastOfflineTimeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\",\n\x19GetLastOfflineTimeRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"7\n\x1aGetLastOfflineTimeResponse\x12\x19\n\x11last_offline_time\x18\x01 \x01(\x03\x32\xd3\x01\n\x16LastOfflineTimeService\x12`\n\x15UpdateLastOfflineTime\x12\".grpc.UpdateLastOfflineTimeRequest\x1a#.grpc.UpdateLastOfflineTimeResponse\x12W\n\x12GetLastOfflineTime\x12\x1f.grpc.GetLastOfflineTimeRequest\x1a .grpc.GetLastOfflineTimeResponseB1Z/infrastructure_sdk/last_offline_time_grpc/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'infrastructure_sdk.grpc.last_offline_time_grpc.proto.last_offline_time_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/infrastructure_sdk/last_offline_time_grpc/proto'
  _globals['_UPDATELASTOFFLINETIMEREQUEST']._serialized_start=86
  _globals['_UPDATELASTOFFLINETIMEREQUEST']._serialized_end=133
  _globals['_UPDATELASTOFFLINETIMERESPONSE']._serialized_start=135
  _globals['_UPDATELASTOFFLINETIMERESPONSE']._serialized_end=183
  _globals['_GETLASTOFFLINETIMEREQUEST']._serialized_start=185
  _globals['_GETLASTOFFLINETIMEREQUEST']._serialized_end=229
  _globals['_GETLASTOFFLINETIMERESPONSE']._serialized_start=231
  _globals['_GETLASTOFFLINETIMERESPONSE']._serialized_end=286
  _globals['_LASTOFFLINETIMESERVICE']._serialized_start=289
  _globals['_LASTOFFLINETIMESERVICE']._serialized_end=500
# @@protoc_insertion_point(module_scope)
