// last_offline_time.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.33.1
// source: infrastructure_sdk/grpc/last_offline_time_grpc/proto/last_offline_time.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 更新用户最后离线时间
type UpdateLastOfflineTimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLastOfflineTimeRequest) Reset() {
	*x = UpdateLastOfflineTimeRequest{}
	mi := &file_infrastructure_sdk_grpc_last_offline_time_grpc_proto_last_offline_time_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLastOfflineTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLastOfflineTimeRequest) ProtoMessage() {}

func (x *UpdateLastOfflineTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infrastructure_sdk_grpc_last_offline_time_grpc_proto_last_offline_time_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLastOfflineTimeRequest.ProtoReflect.Descriptor instead.
func (*UpdateLastOfflineTimeRequest) Descriptor() ([]byte, []int) {
	return file_infrastructure_sdk_grpc_last_offline_time_grpc_proto_last_offline_time_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateLastOfflineTimeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateLastOfflineTimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLastOfflineTimeResponse) Reset() {
	*x = UpdateLastOfflineTimeResponse{}
	mi := &file_infrastructure_sdk_grpc_last_offline_time_grpc_proto_last_offline_time_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLastOfflineTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLastOfflineTimeResponse) ProtoMessage() {}

func (x *UpdateLastOfflineTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_infrastructure_sdk_grpc_last_offline_time_grpc_proto_last_offline_time_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLastOfflineTimeResponse.ProtoReflect.Descriptor instead.
func (*UpdateLastOfflineTimeResponse) Descriptor() ([]byte, []int) {
	return file_infrastructure_sdk_grpc_last_offline_time_grpc_proto_last_offline_time_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateLastOfflineTimeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 获取用户最后离线时间
type GetLastOfflineTimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastOfflineTimeRequest) Reset() {
	*x = GetLastOfflineTimeRequest{}
	mi := &file_infrastructure_sdk_grpc_last_offline_time_grpc_proto_last_offline_time_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastOfflineTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastOfflineTimeRequest) ProtoMessage() {}

func (x *GetLastOfflineTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infrastructure_sdk_grpc_last_offline_time_grpc_proto_last_offline_time_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastOfflineTimeRequest.ProtoReflect.Descriptor instead.
func (*GetLastOfflineTimeRequest) Descriptor() ([]byte, []int) {
	return file_infrastructure_sdk_grpc_last_offline_time_grpc_proto_last_offline_time_proto_rawDescGZIP(), []int{2}
}

func (x *GetLastOfflineTimeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetLastOfflineTimeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LastOfflineTime int64                  `protobuf:"varint,1,opt,name=last_offline_time,json=lastOfflineTime,proto3" json:"last_offline_time,omitempty"` // 时间戳（秒）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetLastOfflineTimeResponse) Reset() {
	*x = GetLastOfflineTimeResponse{}
	mi := &file_infrastructure_sdk_grpc_last_offline_time_grpc_proto_last_offline_time_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastOfflineTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastOfflineTimeResponse) ProtoMessage() {}

func (x *GetLastOfflineTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_infrastructure_sdk_grpc_last_offline_time_grpc_proto_last_offline_time_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastOfflineTimeResponse.ProtoReflect.Descriptor instead.
func (*GetLastOfflineTimeResponse) Descriptor() ([]byte, []int) {
	return file_infrastructure_sdk_grpc_last_offline_time_grpc_proto_last_offline_time_proto_rawDescGZIP(), []int{3}
}

func (x *GetLastOfflineTimeResponse) GetLastOfflineTime() int64 {
	if x != nil {
		return x.LastOfflineTime
	}
	return 0
}

var File_infrastructure_sdk_grpc_last_offline_time_grpc_proto_last_offline_time_proto protoreflect.FileDescriptor

const file_infrastructure_sdk_grpc_last_offline_time_grpc_proto_last_offline_time_proto_rawDesc = "" +
	"\n" +
	"Linfrastructure_sdk/grpc/last_offline_time_grpc/proto/last_offline_time.proto\x12\x04grpc\"7\n" +
	"\x1cUpdateLastOfflineTimeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"9\n" +
	"\x1dUpdateLastOfflineTimeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"4\n" +
	"\x19GetLastOfflineTimeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"H\n" +
	"\x1aGetLastOfflineTimeResponse\x12*\n" +
	"\x11last_offline_time\x18\x01 \x01(\x03R\x0flastOfflineTime2\xd3\x01\n" +
	"\x16LastOfflineTimeService\x12`\n" +
	"\x15UpdateLastOfflineTime\x12\".grpc.UpdateLastOfflineTimeRequest\x1a#.grpc.UpdateLastOfflineTimeResponse\x12W\n" +
	"\x12GetLastOfflineTime\x12\x1f.grpc.GetLastOfflineTimeRequest\x1a .grpc.GetLastOfflineTimeResponseB1Z/infrastructure_sdk/last_offline_time_grpc/protob\x06proto3"

var (
	file_infrastructure_sdk_grpc_last_offline_time_grpc_proto_last_offline_time_proto_rawDescOnce sync.Once
	file_infrastructure_sdk_grpc_last_offline_time_grpc_proto_last_offline_time_proto_rawDescData []byte
)

func file_infrastructure_sdk_grpc_last_offline_time_grpc_proto_last_offline_time_proto_rawDescGZIP() []byte {
	file_infrastructure_sdk_grpc_last_offline_time_grpc_proto_last_offline_time_proto_rawDescOnce.Do(func() {
		file_infrastructure_sdk_grpc_last_offline_time_grpc_proto_last_offline_time_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_infrastructure_sdk_grpc_last_offline_time_grpc_proto_last_offline_time_proto_rawDesc), len(file_infrastructure_sdk_grpc_last_offline_time_grpc_proto_last_offline_time_proto_rawDesc)))
	})
	return file_infrastructure_sdk_grpc_last_offline_time_grpc_proto_last_offline_time_proto_rawDescData
}

var file_infrastructure_sdk_grpc_last_offline_time_grpc_proto_last_offline_time_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_infrastructure_sdk_grpc_last_offline_time_grpc_proto_last_offline_time_proto_goTypes = []any{
	(*UpdateLastOfflineTimeRequest)(nil),  // 0: grpc.UpdateLastOfflineTimeRequest
	(*UpdateLastOfflineTimeResponse)(nil), // 1: grpc.UpdateLastOfflineTimeResponse
	(*GetLastOfflineTimeRequest)(nil),     // 2: grpc.GetLastOfflineTimeRequest
	(*GetLastOfflineTimeResponse)(nil),    // 3: grpc.GetLastOfflineTimeResponse
}
var file_infrastructure_sdk_grpc_last_offline_time_grpc_proto_last_offline_time_proto_depIdxs = []int32{
	0, // 0: grpc.LastOfflineTimeService.UpdateLastOfflineTime:input_type -> grpc.UpdateLastOfflineTimeRequest
	2, // 1: grpc.LastOfflineTimeService.GetLastOfflineTime:input_type -> grpc.GetLastOfflineTimeRequest
	1, // 2: grpc.LastOfflineTimeService.UpdateLastOfflineTime:output_type -> grpc.UpdateLastOfflineTimeResponse
	3, // 3: grpc.LastOfflineTimeService.GetLastOfflineTime:output_type -> grpc.GetLastOfflineTimeResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_infrastructure_sdk_grpc_last_offline_time_grpc_proto_last_offline_time_proto_init() }
func file_infrastructure_sdk_grpc_last_offline_time_grpc_proto_last_offline_time_proto_init() {
	if File_infrastructure_sdk_grpc_last_offline_time_grpc_proto_last_offline_time_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_infrastructure_sdk_grpc_last_offline_time_grpc_proto_last_offline_time_proto_rawDesc), len(file_infrastructure_sdk_grpc_last_offline_time_grpc_proto_last_offline_time_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_infrastructure_sdk_grpc_last_offline_time_grpc_proto_last_offline_time_proto_goTypes,
		DependencyIndexes: file_infrastructure_sdk_grpc_last_offline_time_grpc_proto_last_offline_time_proto_depIdxs,
		MessageInfos:      file_infrastructure_sdk_grpc_last_offline_time_grpc_proto_last_offline_time_proto_msgTypes,
	}.Build()
	File_infrastructure_sdk_grpc_last_offline_time_grpc_proto_last_offline_time_proto = out.File
	file_infrastructure_sdk_grpc_last_offline_time_grpc_proto_last_offline_time_proto_goTypes = nil
	file_infrastructure_sdk_grpc_last_offline_time_grpc_proto_last_offline_time_proto_depIdxs = nil
}
