// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"user_service/app/database/pgsql/model"
)

func newPrivateChat(db *gorm.DB, opts ...gen.DOOption) privateChat {
	_privateChat := privateChat{}

	_privateChat.privateChatDo.UseDB(db, opts...)
	_privateChat.privateChatDo.UseModel(&model.PrivateChat{})

	tableName := _privateChat.privateChatDo.TableName()
	_privateChat.ALL = field.NewAsterisk(tableName)
	_privateChat.UserID = field.NewString(tableName, "user_id")
	_privateChat.AddTime = field.NewTime(tableName, "add_time")

	_privateChat.fillFieldMap()

	return _privateChat
}

type privateChat struct {
	privateChatDo privateChatDo

	ALL     field.Asterisk
	UserID  field.String
	AddTime field.Time

	fieldMap map[string]field.Expr
}

func (p privateChat) Table(newTableName string) *privateChat {
	p.privateChatDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p privateChat) As(alias string) *privateChat {
	p.privateChatDo.DO = *(p.privateChatDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *privateChat) updateTableName(table string) *privateChat {
	p.ALL = field.NewAsterisk(table)
	p.UserID = field.NewString(table, "user_id")
	p.AddTime = field.NewTime(table, "add_time")

	p.fillFieldMap()

	return p
}

func (p *privateChat) WithContext(ctx context.Context) IPrivateChatDo {
	return p.privateChatDo.WithContext(ctx)
}

func (p privateChat) TableName() string { return p.privateChatDo.TableName() }

func (p privateChat) Alias() string { return p.privateChatDo.Alias() }

func (p privateChat) Columns(cols ...field.Expr) gen.Columns { return p.privateChatDo.Columns(cols...) }

func (p *privateChat) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *privateChat) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 2)
	p.fieldMap["user_id"] = p.UserID
	p.fieldMap["add_time"] = p.AddTime
}

func (p privateChat) clone(db *gorm.DB) privateChat {
	p.privateChatDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p privateChat) replaceDB(db *gorm.DB) privateChat {
	p.privateChatDo.ReplaceDB(db)
	return p
}

type privateChatDo struct{ gen.DO }

type IPrivateChatDo interface {
	gen.SubQuery
	Debug() IPrivateChatDo
	WithContext(ctx context.Context) IPrivateChatDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPrivateChatDo
	WriteDB() IPrivateChatDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPrivateChatDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPrivateChatDo
	Not(conds ...gen.Condition) IPrivateChatDo
	Or(conds ...gen.Condition) IPrivateChatDo
	Select(conds ...field.Expr) IPrivateChatDo
	Where(conds ...gen.Condition) IPrivateChatDo
	Order(conds ...field.Expr) IPrivateChatDo
	Distinct(cols ...field.Expr) IPrivateChatDo
	Omit(cols ...field.Expr) IPrivateChatDo
	Join(table schema.Tabler, on ...field.Expr) IPrivateChatDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPrivateChatDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPrivateChatDo
	Group(cols ...field.Expr) IPrivateChatDo
	Having(conds ...gen.Condition) IPrivateChatDo
	Limit(limit int) IPrivateChatDo
	Offset(offset int) IPrivateChatDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPrivateChatDo
	Unscoped() IPrivateChatDo
	Create(values ...*model.PrivateChat) error
	CreateInBatches(values []*model.PrivateChat, batchSize int) error
	Save(values ...*model.PrivateChat) error
	First() (*model.PrivateChat, error)
	Take() (*model.PrivateChat, error)
	Last() (*model.PrivateChat, error)
	Find() ([]*model.PrivateChat, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PrivateChat, err error)
	FindInBatches(result *[]*model.PrivateChat, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PrivateChat) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPrivateChatDo
	Assign(attrs ...field.AssignExpr) IPrivateChatDo
	Joins(fields ...field.RelationField) IPrivateChatDo
	Preload(fields ...field.RelationField) IPrivateChatDo
	FirstOrInit() (*model.PrivateChat, error)
	FirstOrCreate() (*model.PrivateChat, error)
	FindByPage(offset int, limit int) (result []*model.PrivateChat, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPrivateChatDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p privateChatDo) Debug() IPrivateChatDo {
	return p.withDO(p.DO.Debug())
}

func (p privateChatDo) WithContext(ctx context.Context) IPrivateChatDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p privateChatDo) ReadDB() IPrivateChatDo {
	return p.Clauses(dbresolver.Read)
}

func (p privateChatDo) WriteDB() IPrivateChatDo {
	return p.Clauses(dbresolver.Write)
}

func (p privateChatDo) Session(config *gorm.Session) IPrivateChatDo {
	return p.withDO(p.DO.Session(config))
}

func (p privateChatDo) Clauses(conds ...clause.Expression) IPrivateChatDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p privateChatDo) Returning(value interface{}, columns ...string) IPrivateChatDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p privateChatDo) Not(conds ...gen.Condition) IPrivateChatDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p privateChatDo) Or(conds ...gen.Condition) IPrivateChatDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p privateChatDo) Select(conds ...field.Expr) IPrivateChatDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p privateChatDo) Where(conds ...gen.Condition) IPrivateChatDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p privateChatDo) Order(conds ...field.Expr) IPrivateChatDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p privateChatDo) Distinct(cols ...field.Expr) IPrivateChatDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p privateChatDo) Omit(cols ...field.Expr) IPrivateChatDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p privateChatDo) Join(table schema.Tabler, on ...field.Expr) IPrivateChatDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p privateChatDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPrivateChatDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p privateChatDo) RightJoin(table schema.Tabler, on ...field.Expr) IPrivateChatDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p privateChatDo) Group(cols ...field.Expr) IPrivateChatDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p privateChatDo) Having(conds ...gen.Condition) IPrivateChatDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p privateChatDo) Limit(limit int) IPrivateChatDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p privateChatDo) Offset(offset int) IPrivateChatDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p privateChatDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPrivateChatDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p privateChatDo) Unscoped() IPrivateChatDo {
	return p.withDO(p.DO.Unscoped())
}

func (p privateChatDo) Create(values ...*model.PrivateChat) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p privateChatDo) CreateInBatches(values []*model.PrivateChat, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p privateChatDo) Save(values ...*model.PrivateChat) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p privateChatDo) First() (*model.PrivateChat, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrivateChat), nil
	}
}

func (p privateChatDo) Take() (*model.PrivateChat, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrivateChat), nil
	}
}

func (p privateChatDo) Last() (*model.PrivateChat, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrivateChat), nil
	}
}

func (p privateChatDo) Find() ([]*model.PrivateChat, error) {
	result, err := p.DO.Find()
	return result.([]*model.PrivateChat), err
}

func (p privateChatDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PrivateChat, err error) {
	buf := make([]*model.PrivateChat, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p privateChatDo) FindInBatches(result *[]*model.PrivateChat, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p privateChatDo) Attrs(attrs ...field.AssignExpr) IPrivateChatDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p privateChatDo) Assign(attrs ...field.AssignExpr) IPrivateChatDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p privateChatDo) Joins(fields ...field.RelationField) IPrivateChatDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p privateChatDo) Preload(fields ...field.RelationField) IPrivateChatDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p privateChatDo) FirstOrInit() (*model.PrivateChat, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrivateChat), nil
	}
}

func (p privateChatDo) FirstOrCreate() (*model.PrivateChat, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrivateChat), nil
	}
}

func (p privateChatDo) FindByPage(offset int, limit int) (result []*model.PrivateChat, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p privateChatDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p privateChatDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p privateChatDo) Delete(models ...*model.PrivateChat) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *privateChatDo) withDO(do gen.Dao) *privateChatDo {
	p.DO = *do.(*gen.DO)
	return p
}
