// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"user_service/app/database/pgsql/model"
)

func newTempChat(db *gorm.DB, opts ...gen.DOOption) tempChat {
	_tempChat := tempChat{}

	_tempChat.tempChatDo.UseDB(db, opts...)
	_tempChat.tempChatDo.UseModel(&model.TempChat{})

	tableName := _tempChat.tempChatDo.TableName()
	_tempChat.ALL = field.NewAsterisk(tableName)
	_tempChat.UserID = field.NewString(tableName, "user_id")
	_tempChat.Source = field.NewString(tableName, "source")

	_tempChat.fillFieldMap()

	return _tempChat
}

type tempChat struct {
	tempChatDo tempChatDo

	ALL    field.Asterisk
	UserID field.String
	Source field.String

	fieldMap map[string]field.Expr
}

func (t tempChat) Table(newTableName string) *tempChat {
	t.tempChatDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tempChat) As(alias string) *tempChat {
	t.tempChatDo.DO = *(t.tempChatDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tempChat) updateTableName(table string) *tempChat {
	t.ALL = field.NewAsterisk(table)
	t.UserID = field.NewString(table, "user_id")
	t.Source = field.NewString(table, "source")

	t.fillFieldMap()

	return t
}

func (t *tempChat) WithContext(ctx context.Context) ITempChatDo { return t.tempChatDo.WithContext(ctx) }

func (t tempChat) TableName() string { return t.tempChatDo.TableName() }

func (t tempChat) Alias() string { return t.tempChatDo.Alias() }

func (t tempChat) Columns(cols ...field.Expr) gen.Columns { return t.tempChatDo.Columns(cols...) }

func (t *tempChat) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tempChat) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 2)
	t.fieldMap["user_id"] = t.UserID
	t.fieldMap["source"] = t.Source
}

func (t tempChat) clone(db *gorm.DB) tempChat {
	t.tempChatDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tempChat) replaceDB(db *gorm.DB) tempChat {
	t.tempChatDo.ReplaceDB(db)
	return t
}

type tempChatDo struct{ gen.DO }

type ITempChatDo interface {
	gen.SubQuery
	Debug() ITempChatDo
	WithContext(ctx context.Context) ITempChatDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITempChatDo
	WriteDB() ITempChatDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITempChatDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITempChatDo
	Not(conds ...gen.Condition) ITempChatDo
	Or(conds ...gen.Condition) ITempChatDo
	Select(conds ...field.Expr) ITempChatDo
	Where(conds ...gen.Condition) ITempChatDo
	Order(conds ...field.Expr) ITempChatDo
	Distinct(cols ...field.Expr) ITempChatDo
	Omit(cols ...field.Expr) ITempChatDo
	Join(table schema.Tabler, on ...field.Expr) ITempChatDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITempChatDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITempChatDo
	Group(cols ...field.Expr) ITempChatDo
	Having(conds ...gen.Condition) ITempChatDo
	Limit(limit int) ITempChatDo
	Offset(offset int) ITempChatDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITempChatDo
	Unscoped() ITempChatDo
	Create(values ...*model.TempChat) error
	CreateInBatches(values []*model.TempChat, batchSize int) error
	Save(values ...*model.TempChat) error
	First() (*model.TempChat, error)
	Take() (*model.TempChat, error)
	Last() (*model.TempChat, error)
	Find() ([]*model.TempChat, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TempChat, err error)
	FindInBatches(result *[]*model.TempChat, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TempChat) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITempChatDo
	Assign(attrs ...field.AssignExpr) ITempChatDo
	Joins(fields ...field.RelationField) ITempChatDo
	Preload(fields ...field.RelationField) ITempChatDo
	FirstOrInit() (*model.TempChat, error)
	FirstOrCreate() (*model.TempChat, error)
	FindByPage(offset int, limit int) (result []*model.TempChat, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITempChatDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tempChatDo) Debug() ITempChatDo {
	return t.withDO(t.DO.Debug())
}

func (t tempChatDo) WithContext(ctx context.Context) ITempChatDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tempChatDo) ReadDB() ITempChatDo {
	return t.Clauses(dbresolver.Read)
}

func (t tempChatDo) WriteDB() ITempChatDo {
	return t.Clauses(dbresolver.Write)
}

func (t tempChatDo) Session(config *gorm.Session) ITempChatDo {
	return t.withDO(t.DO.Session(config))
}

func (t tempChatDo) Clauses(conds ...clause.Expression) ITempChatDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tempChatDo) Returning(value interface{}, columns ...string) ITempChatDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tempChatDo) Not(conds ...gen.Condition) ITempChatDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tempChatDo) Or(conds ...gen.Condition) ITempChatDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tempChatDo) Select(conds ...field.Expr) ITempChatDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tempChatDo) Where(conds ...gen.Condition) ITempChatDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tempChatDo) Order(conds ...field.Expr) ITempChatDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tempChatDo) Distinct(cols ...field.Expr) ITempChatDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tempChatDo) Omit(cols ...field.Expr) ITempChatDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tempChatDo) Join(table schema.Tabler, on ...field.Expr) ITempChatDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tempChatDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITempChatDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tempChatDo) RightJoin(table schema.Tabler, on ...field.Expr) ITempChatDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tempChatDo) Group(cols ...field.Expr) ITempChatDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tempChatDo) Having(conds ...gen.Condition) ITempChatDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tempChatDo) Limit(limit int) ITempChatDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tempChatDo) Offset(offset int) ITempChatDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tempChatDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITempChatDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tempChatDo) Unscoped() ITempChatDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tempChatDo) Create(values ...*model.TempChat) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tempChatDo) CreateInBatches(values []*model.TempChat, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tempChatDo) Save(values ...*model.TempChat) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tempChatDo) First() (*model.TempChat, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TempChat), nil
	}
}

func (t tempChatDo) Take() (*model.TempChat, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TempChat), nil
	}
}

func (t tempChatDo) Last() (*model.TempChat, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TempChat), nil
	}
}

func (t tempChatDo) Find() ([]*model.TempChat, error) {
	result, err := t.DO.Find()
	return result.([]*model.TempChat), err
}

func (t tempChatDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TempChat, err error) {
	buf := make([]*model.TempChat, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tempChatDo) FindInBatches(result *[]*model.TempChat, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tempChatDo) Attrs(attrs ...field.AssignExpr) ITempChatDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tempChatDo) Assign(attrs ...field.AssignExpr) ITempChatDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tempChatDo) Joins(fields ...field.RelationField) ITempChatDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tempChatDo) Preload(fields ...field.RelationField) ITempChatDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tempChatDo) FirstOrInit() (*model.TempChat, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TempChat), nil
	}
}

func (t tempChatDo) FirstOrCreate() (*model.TempChat, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TempChat), nil
	}
}

func (t tempChatDo) FindByPage(offset int, limit int) (result []*model.TempChat, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tempChatDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tempChatDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tempChatDo) Delete(models ...*model.TempChat) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tempChatDo) withDO(do gen.Dao) *tempChatDo {
	t.DO = *do.(*gen.DO)
	return t
}
